window.CRECHE_FIREBASE = {
  projectId: "creche-5900b",
  projectNumber: "681463851405",
  appId: "1:681463851405:web:f6ae33163e8b6e4a81b5c4",
  apiKey: "AIzaSyCYBNL5XnwqZOQtDgVKX1GEWoz3T59vxXs",
  authDomain: "creche-5900b.firebaseapp.com",
  storageBucket: "creche-5900b.firebasestorage.app",
  messagingSenderId: "681463851405",
  enabled: true,
  authMode: "email-password",
  bootstrapAdminEmail: "admin@bronks.ia.br",
  schoolCollection: "schools",
  schoolDocument: "creche-5900b",
  metaCollection: "system",
  metaDocument: "meta",
  collections: {
    students: "students",
    staff: "staff",
    tuition: "tuition",
    delinquency: "delinquency",
    extras: "extras",
    receivables: "receivables",
    payables: "payables",
    taxes: "taxes",
    reportCards: "reportCards",
    classes: "classes",
    profiles: "profiles",
    users: "users",
    invites: "invites",
    diary: "diary",
    attendance: "attendance",
    health: "health",
    incidents: "incidents"
  }
};
