server {
    listen 5500;
    server_name 148.230.79.134;

    root /var/www/creche;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Custom handling for SPA if needed (uncomment if you add routing)
    # location / {
    #     try_files $uri $uri/ /index.html;
    # }

    location ~ /\. {
        deny all;
    }

    error_page 404 /index.html;
}
